### PR TITLE
fix issues with Autoptimize

### PR DESCRIPTION
**Pull request by futtta**
If AO is active hook into AO's filters to:
* get full HTML (iso fiddling with the output buffer)
* exclude the ginger JS from AO optimization

### CODE REVIEW

**Comment by paolobros** [comment]
Hi,
Which exact files?

**Comment by futtta** [comment]
click on "[files changed](https://github.com/webgrafia/ginger/pull/32/files)" @paolobros :-)

**Comment by paolobros** [comment]
Ok ! Perfect. Thank You!

**Comment by futtta** [comment]
Going to do a new PR, there's some issues with the code @webgrafia

**Pull request merged**
